const CALENDAR_SLOT_HEIGHT = 66;
const CALENDAR_MOBILE_SLOT_HEIGHT = 58;
const CALENDAR_TASK_INSET_TOP = 8;
const CALENDAR_TASK_INSET_SIDE = 8;
const CALENDAR_TASK_INSET_BOTTOM = 6;

export {
  CALENDAR_SLOT_HEIGHT,
  CALENDAR_MOBILE_SLOT_HEIGHT,
  CALENDAR_TASK_INSET_TOP,
  CALENDAR_TASK_INSET_SIDE,
  CALENDAR_TASK_INSET_BOTTOM
};
